apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jenkins.fullname" . }}-cm-v2
data:
  jenkins-config.yaml: |-
    jenkins:
      systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
      globalNodeProperties:
      - envVars:
          env:
          - key: VARIABLE1
            value: foo
          - key: VARIABLE2
            value: bar
      nodes:
        - permanent:
            name: "static-agent"
            remoteFS: "/home/jenkins"
            launcher:
              jnlp:
                workDirSettings:
                  disabled: true
                  failIfWorkDirIsMissing: false
                  internalDir: "remoting"
                  workDirPath: "/tmp"