replicaCount: 1

image:
  repository: kadirzade/sh2-jenkins
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources: 
  limits:
    cpu: 120m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 256Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""    

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}

# probes:
#   liveness:
#     path: /hc/live
#     initialDelaySeconds: 10
#     periodSeconds: 30
#     port: 80
#   readiness:
#     path: /hc/ready
#     timeoutSeconds: 5
#     initialDelaySeconds: 30
#     periodSeconds: 10
#     failureThreshold: 4
#     successThreshold: 1
#     port: 80
